global using System.Net;
global using System.Net.Http.Headers;
global using System.Text.Json;
global using System.Text.Json.Serialization;
global using Microsoft.Extensions.DependencyInjection;
global using Microsoft.Extensions.DependencyInjection.Extensions;
global using Microsoft.Extensions.Http;
global using Microsoft.Maui.Hosting;
global using Plugin.Maui.SecureStoragePlus;
